#!/usr/bin/env python3
"""Assemble the Firefox policies and the local web filter into the airootfs.

The public repo ships the base Firefox policy (firefox/policies.json) and nothing
else about the filter. The lab-specific part lives in the private, gitignored
overlay distro/filter/:
    firefox-policies.json   the private policy fragment (keys merged into the base)
    airootfs/               the private overlay (files copied over profile/airootfs/)
    gerar.py                the private generator (writes the local filter config)
Everything written under profile/ is generated and gitignored, so it is deleted
first: a build without the overlay must not leak a stale filter from an earlier one.
The overlay may only contain files under etc/NetworkManager/, which is generated
and wiped on every run.

Run from distro/:  python3 scripts/stage-filter.py   (or `just filter`)
NO_FILTER=1 skips the overlay entirely and builds an image with no web filter.
"""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

DISTRO = Path(__file__).resolve().parent.parent
PROFILE = DISTRO / "profile/airootfs"
FILTER = DISTRO / "filter"
BASE_POLICY = DISTRO / "firefox/policies.json"
POLICY_OUT = PROFILE / "etc/firefox/policies/policies.json"

# What the private overlay must contain to be staged.
OVERLAY_FILES = ("gerar.py", "firefox-policies.json", "airootfs/")

# The only directory the overlay may write to, and the only one it is copied to.
OVERLAY_SUBDIR = "etc/NetworkManager"

# Generated by this script or by the private generator; all gitignored.
GENERATED = [
    PROFILE / "etc/NetworkManager",
    PROFILE / "etc/firefox/policies",
]


def clean_generated():
    """Delete the generated paths, which never hold tracked files."""
    for path in GENERATED:
        shutil.rmtree(path, ignore_errors=True)


def check_overlay():
    """Refuse overlay entries outside etc/NetworkManager/.

    Anything else would land in a path that is not gitignored, or overwrite a
    public profile file. Symlinks count as entries; the walk does not descend
    into symlinked directories. The deepest offending entry is reported, so an
    out-of-bounds tree names the entry it actually adds (a file, a symlink or an
    empty directory) rather than its top-level ancestor.
    """
    src = FILTER / "airootfs"
    allowed = Path(OVERLAY_SUBDIR)
    offender = None
    for root, dirs, files in os.walk(src, followlinks=False):
        for name in sorted(files + dirs):
            rel = (Path(root) / name).relative_to(src)
            if not (rel.is_relative_to(allowed) or allowed.is_relative_to(rel)):
                if offender is None or len(rel.parts) > len(offender.parts):
                    offender = rel
    if offender is not None:
        sys.exit(f"distro/filter/airootfs/{offender}: arquivos do filtro só podem "
                 f"ficar em {OVERLAY_SUBDIR}/")


def stage_policy():
    """Load the base policy and merge the private fragment into it."""
    with BASE_POLICY.open(encoding="utf-8") as f:
        policy = json.load(f)

    if os.environ.get("NO_FILTER") == "1":
        print("AVISO: NO_FILTER=1 — a imagem será gerada SEM filtro de sites.",
              file=sys.stderr)
    elif not FILTER.is_dir():
        sys.exit("distro/filter/ não encontrado: a imagem ficaria sem filtro de sites. "
                 "Para gerar mesmo assim: NO_FILTER=1 just build")
    else:
        for name in OVERLAY_FILES:
            if not (FILTER / name).exists():
                sys.exit(f"distro/filter/ incompleto: falta {name}")

        check_overlay()
        subprocess.run([sys.executable, str(FILTER / "gerar.py")], check=True)
        with (FILTER / "firefox-policies.json").open(encoding="utf-8") as f:
            extra = json.load(f)["policies"]
        for key, value in extra.items():
            if key in policy["policies"]:
                sys.exit(f"erro: a política '{key}' está definida em firefox/policies.json "
                         f"e em filter/firefox-policies.json")
            policy["policies"][key] = value
        shutil.copytree(FILTER / "airootfs", PROFILE, dirs_exist_ok=True)
        print("filtro de sites: incluído")

    POLICY_OUT.parent.mkdir(parents=True, exist_ok=True)
    with POLICY_OUT.open("w", encoding="utf-8") as f:
        json.dump(policy, f, indent=2, ensure_ascii=False)
        f.write("\n")
    POLICY_OUT.chmod(0o644)


def main():
    clean_generated()
    stage_policy()


if __name__ == "__main__":
    main()
