title   ScratchLab (copiar para RAM, pode tirar o pendrive)
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=1G copytoram=y quiet splash plymouth.use-simpledrm cfg80211.ieee80211_regdom=BR loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0
